// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RK_A11.DB;

#nullable disable

namespace RK_A11.Migrations
{
    [DbContext(typeof(InventoryContext))]
    partial class InventoryContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("ProductSchema")
                .HasAnnotation("ProductVersion", "6.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("RK_A11.Entities.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"), 1L, 1);

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CategoryName");

                    b.HasKey("CategoryId");

                    b.ToTable("CategoryInfo", "ProductSchema");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CategoryName = "Consumables"
                        },
                        new
                        {
                            CategoryId = 2,
                            CategoryName = "Electronics"
                        },
                        new
                        {
                            CategoryId = 3,
                            CategoryName = "Decorations"
                        });
                });

            modelBuilder.Entity("RK_A11.Entities.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"), 1L, 1);

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Manufacture")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProductId");

                    b.HasIndex("CategoryId");

                    b.ToTable("ProductInfo", "ProductSchema");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            CategoryId = 1,
                            Manufacture = "Pizza Hut",
                            ProductName = "Pizza"
                        },
                        new
                        {
                            ProductId = 2,
                            CategoryId = 2,
                            Manufacture = "Apple",
                            ProductName = "Airpods"
                        },
                        new
                        {
                            ProductId = 3,
                            CategoryId = 1,
                            Manufacture = "Red Bull",
                            ProductName = "Red bull Energy Drink"
                        },
                        new
                        {
                            ProductId = 4,
                            CategoryId = 3,
                            Manufacture = "IKEA",
                            ProductName = "Curtain"
                        },
                        new
                        {
                            ProductId = 5,
                            CategoryId = 2,
                            Manufacture = "Bose",
                            ProductName = "Bose QC 35 II"
                        },
                        new
                        {
                            ProductId = 6,
                            CategoryId = 3,
                            Manufacture = "Seiko",
                            ProductName = "Wall Clock"
                        });
                });

            modelBuilder.Entity("RK_A11.Entities.Product", b =>
                {
                    b.HasOne("RK_A11.Entities.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("RK_A11.Entities.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
